# Generated by Django 3.1.7 on 2021-05-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(max_length=50)),
                ('Cat_des', models.TextField()),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('OTP', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=50)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Businesstype', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Profile_pic', models.ImageField(default='abc.jpg', upload_to='img/')),
                ('Shopname', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Profile_pic', models.ImageField(default='1.jpg', upload_to='img/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('Book_name', models.CharField(max_length=50)),
                ('Book_Des', models.CharField(max_length=50)),
                ('Book_price', models.CharField(max_length=50)),
                ('MainImage', models.ImageField(upload_to='img/')),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller')),
                ('sub_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='BookGellery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img1', models.ImageField(upload_to='img/')),
                ('book_img2', models.ImageField(upload_to='img/')),
                ('book_img3', models.ImageField(upload_to='img/')),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
                ('book_t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booktable')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=50)),
                ('Author_des', models.CharField(max_length=200)),
                ('Book_Pages', models.IntegerField()),
                ('Book_lang', models.CharField(max_length=50)),
                ('Book_Publish', models.CharField(max_length=50)),
                ('Book_Pub_Date', models.CharField(max_length=50)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
                ('book_t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booktable')),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('SubTotal', models.IntegerField()),
                ('Book', models.CharField(max_length=50)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('update_Date', models.DateTimeField(auto_now_add=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booktable')),
            ],
        ),
    ]
